name: Pylint


env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
  TEST_ENV: true
  SECRET_KEY: sekret


on:
  push:
    branches:
      - "mlenni-patch"
  pull_request:
    branches:
      - "main" 
    paths:
      - ".github/workflows/pylint.yml"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint src/
